name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  pre-commit:
    name: Run pre-commit hooks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install uv
      run: |
        python -m pip install --upgrade pip
        pip install uv

    - name: Create virtual environment
      run: uv venv

    - name: Install dependencies
      run: |
        source .venv/bin/activate
        uv pip install -r requirements.lock
        uv pip install -e .

    - name: Install pre-commit
      run: |
        source .venv/bin/activate
        uv pip install pre-commit

    - name: Run pre-commit
      run: |
        source .venv/bin/activate
        pre-commit run --all-files
